version: 2

# https://circleci.com/docs/2.0/language-javascript/
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

whitelist: &whitelist
  paths:
    - .npmignore
    - .gitignore
    - tsconfig.*
    - LICENSE
    - package.json
    - package-lock.json
    - __mocks__/*
    - build/*
    - node_modules/*
    - src/*
    - scripts/*
    - tslint.json
    - coverage/*
    - .git/*

save: &save
  persist_to_workspace:
    root: ~/repo
    <<: *whitelist

restore: &restore
  attach_workspace:
    at: ~/repo

jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      # saves to the local node_modules, which gets passed through all jobs
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - <<: *save

  test:
    <<: *defaults

    steps:
      - <<: *restore

      - run:
          name: Lint
          command: npm run test:lint

      - run:
          name: Unit Test
          command: npm run test:unit:ci
          environment:
            JEST_JUNIT_OUTPUT: "reports/jest/js-test-results.xml"

      - run:
          name: Security Check
          command: npm run test:security

      - store_test_results:
          path: "reports"

  coverage:
    <<: *defaults

    steps:
      - <<: *restore

      - run:
          name: Run coverage check
          command: npx jest --coverage --coverageReporters='lcov'

      - run:
          name: Upload coverage result to codecov
          # circleci bash doesn't expand the home tilde
          command: '[ -d "${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"/coverage ] && npx codecov'
          when: always

  build:
    <<: *defaults

    steps:
      - <<: *restore

      - run:
          name: Build Typescript
          command: npm run build

      - <<: *save

  greenkeeper:
    <<: *defaults

    steps:
      - <<: *restore

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - coverage:
          requires:
            - checkout
      - build:
          requires:
            - test
      - greenkeeper:
          requires:
            - build
